In [3]:
from urllib.request import urlopen
from bs4 import BeautifulSoup

In [4]:
url = "https://www.wunderground.com/history/airport/KBUF/2016/1/1/DailyHistory.html"
page = urlopen(url)

# Get temperature from page
soup = BeautifulSoup(page, "html.parser")
# dayTemp = soup.body.nobr.b.string
dayTemp = soup.find_all(attrs={"class":"wx-value"})[0].string 
dayTemp

'29'

## Scrape three values¶

In [5]:
import numpy as np

dayTemp = np.empty(3)

print(dayTemp)

[  2.68156159e+154   2.32035385e+077   2.22975339e-314]


In [6]:

url = "https://www.wunderground.com/history/airport/KBUF/2016/1/1/DailyHistory.html"
page = urlopen(url)
 
# Get temperature from page
soup = BeautifulSoup(page, "html.parser")
# dayTemp = soup.body.nobr.b.string
dayTemp[0] = soup.find_all(attrs={"class":"wx-value"})[0].string 

url = "https://www.wunderground.com/history/airport/KBUF/2016/1/2/DailyHistory.html"
page = urlopen(url)
 
# Get temperature from page
soup = BeautifulSoup(page, "html.parser")
# dayTemp = soup.body.nobr.b.string
dayTemp[1] = soup.find_all(attrs={"class":"wx-value"})[0].string 

url = "https://www.wunderground.com/history/airport/KBUF/2016/1/3/DailyHistory.html"
page = urlopen(url)
 
# Get temperature from page
soup = BeautifulSoup(page, "html.parser")
# dayTemp = soup.body.nobr.b.string
dayTemp[2] = soup.find_all(attrs={"class":"wx-value"})[0].string 

print(dayTemp)

[ 29.  30.  28.]


In [7]:
index = 0

for d in range(1, 4):
    url = "https://www.wunderground.com/history/airport/KBUF/2016/1/" + str(d) + "/DailyHistory.html"
    page = urlopen(url)
 
    # Get temperature from page
    soup = BeautifulSoup(page, "html.parser")
    # dayTemp = soup.body.nobr.b.string
    
    index = d-1
    
    dayTemp[index] = soup.find_all(attrs={"class":"wx-value"})[0].string 
    
print(dayTemp)

[ 29.  30.  28.]


## Scrape full year of data¶

In [8]:
import numpy as np

dayTemp = np.empty(366)

In [ ]:
index = 0
 
# Iterate through months and day
for m in range(1, 13):
    for d in range(1, 32):
 
      # Check if already gone through month
      if (m == 2 and d > 29):
        break
      elif (m in [4, 6, 9, 11] and d > 30):
        break
 
      # Open wunderground.com url
      url = "https://www.wunderground.com/history/airport/KBUF/2016/" + str(m) + "/" + str(d) + "/DailyHistory.html"
      page = urlopen(url)
 
      # Get temperature from page
      soup = BeautifulSoup(page, "html.parser")
      # dayTemp = soup.body.nobr.b.string
      dayTemp[index] = soup.find_all(attrs={"class":"wx-value"})[0].string 
        
      index = index + 1
 
print(dayTemp)

In [ ]:
print(dayTemp)

## Read data and plot¶

In [ ]:
import pandas as pd

buffalo = pd.DataFrame(dayTemp, columns=['Temp'])

dates = pd.date_range('1/1/2016', periods=366)

buffalo = buffalo.set_index(dates)

print(buffalo.head(5))
print(buffalo.tail(5))

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
# plot
plt.plot(buffalo.Temp)
# beautify the x-labels
plt.gcf().autofmt_xdate()

plt.show()

In [ ]:
import seaborn as sns

In [ ]:
sns.tsplot(data = buffalo.Temp)

plt.show()

In [ ]:
from ggplot import *


In [ ]:
buffalo['Date'] = buffalo.index

ggplot(aes(x='Date', y='Temp'), data=buffalo) + \
    geom_line(color='blue')